[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc_version = '0.8.21'
auto_detect_solc = false
evm_version = 'cancun'

remappings=[
    "@boring-vault=lib/boring-vault/",
    "@solmate=lib/solmate/src",
    "forge-std/=lib/boring-vault/lib/forge-std/src/"
    ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
